[supervisord]
nodaemon=true

[program:apache]
command=apache2-foreground
autostart=true
autorestart=true

[program:websocket]
command=php /var/www/html/server.php
autostart=true
autorestart=true